#!/nix/store/hrpvwkjz04s9i4nmli843hyw9z4pwhww-bash-4.4-p23/bin/sh
picom &
nitrogen --set-scaled ~/Pictures/xfce-blue.jpg &
polybar example &

sxhkd &

bspc monitor -d Alpha Bravo Charlie Delta Echo Foxtrot Golf Hotel India Juliett

bspc config border_width         1
bspc config window_gap           8

bspc config ignore_ewmh_focus    true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config automatic_scheme     longest_side

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Firefox desktop='^9'

